version: "3.8"

services:
  onsquad-cache:
    container_name: onsquad-cache
    image: redis:7.0.8-alpine
    restart: always
    ports:
      - "6379:6379"

  onsquad-aws:
    container_name: onsquad-aws
    image: localstack/localstack:0.14.3
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - SSL_DISABLE=1
      - PORT_WEB_UI=4567
      - AWS_ACCESS_KEY_ID=access-key
      - AWS_SECRET_ACCESS_KEY=secret-key
      - AWS_DEFAULT_REGION=ap-northeast-2
