spring:
  application:
    name: onsquad
  profiles:
    default: local

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:h2:tcp://localhost/~/onsquad;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      resolve-lazily: true

server:
  error:
    whitelabel:
      enabled: false
    include-exception: false
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
  port: 8083

logging:
  level:
    org:
      hibernate:
        SQL: debug