name: ci/cd

on:
  push:
    branches: ['main']
  workflow_dispatch:

env:
  PROJECT_NAME: onsquad

jobs:
  onsquad-server:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout to project
        uses: actions/checkout@v3
          
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make application-dev.yml & application-prod.yml
        run: |
          cd ./src/main/resources
          echo "${{ secrets.APPLICATION_DEV }}" > ./application-dev.yml
          echo "${{ secrets.APPLICATION_PROD }}" > ./application-prod.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./Dockerfile
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}

      - name: Make Docker-Compose.yml
        run: |
          echo "${{ secrets.DOCKER_COMPOSE }}" > ./docker-compose.yml

      - name: Delivery docker-compose.yml
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: 'docker-compose.yml'
          target: 'onsquad'
          rm: true
