name: ci/cd

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

env:
  PROJECT_NAME: onsquad

jobs:
  onsquad-server:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout to project
        uses: actions/checkout@v3

      - name: Start containers
        run: docker compose -f "docker-compose.yml" up -d

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make application-dev.yml & application-prod.yml
        run: |
          cd ./src/main/resources
          printf "%s" "${{ secrets.APPLICATION_DEV }}" > ./application-dev.yml
          printf "%s" "${{ secrets.APPLICATION_PROD }}" > ./application-prod.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build            # run: ./gradlew clean build -Pprofile=ci

      - name: Delivery Executable JAR
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: 'build/libs/*.jar'
          target: ${{ env.PROJECT_NAME }}
          rm: true

      - name: Execute Jar
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            SOURCE_DIR=$(echo $HOME)/${{ env.PROJECT_NAME }}
            EXECUTABLE_SPRING_JAR_PATH=$(find $SOURCE_DIR -name '*.jar' 2>/dev/null)
            PROCESS_ID=$(ps aux | grep -i 'java -jar' | grep -v grep | tr ' ' '\n' | sed -e '/^$/d' | head -2 | tail -1)
            if [[ -z $PROCESS_ID ]]; then
                echo "Nothing Process Running"
            else
                echo "Another Process Running"
                kill -9 $PROCESS_ID
            fi
            nohup java --enable-preview -jar -Duser.timezone=Asia/Seoul -Dspring.profiles.active=${{ secrets.SPRING_PROFILE }} $EXECUTABLE_SPRING_JAR_PATH > $SOURCE_DIR/build/libs/output.log 2>&1 &
            sleep 1
