name: ci/cd

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

env:
  PROJECT_NAME: onsquad

jobs:
  onsquad-server:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout to project
        uses: actions/checkout@v3

      - name: Start containers
        run: docker compose -f 'docker-compose.yml' up -d

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make application-dev.yml & application-prod.yml
        run: |
          cd ./src/main/resources
          echo '${{ secrets.APPLICATION_DEV }}' | base64 -d > ./application-dev.yml
          echo '${{ secrets.APPLICATION_PROD }}' | base64 -d > ./application-prod.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build            # run: ./gradlew clean build -Pprofile=ci

      - name: Delivery Executable JAR
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: 'build/libs/*.jar'
          strip_components: 2
          target: /home/${{secrets.USERNAME}}/${{ env.PROJECT_NAME }}

      - name: Execute Jar
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            BACKUP_DIR=$(echo $HOME)/${{ env.PROJECT_NAME }}/backup
            BACKUP_TMP_DIR='tmp/backup'
            if [[ ! -d $BACKUP_DIR ]]; then
                mkdir -p $BACKUP_DIR
            fi
            if [[ ! -f $BACKUP_DIR/recycle_bin_backup.txt ]]; then
                echo '' > $BACKUP_DIR/recycle_bin_backup.txt
            fi
            if [[ ! -f $BACKUP_DIR/verification_backup.json ]]; then
                echo '{"snapshots":[]}' > $BACKUP_DIR/verification_backup.json
            fi
            
            SOURCE_DIR=$(echo $HOME)/${{ env.PROJECT_NAME }}
            EXECUTABLE_SPRING_JAR_PATH=$(find $SOURCE_DIR -name '*.jar' 2>/dev/null)
            PROCESS_ID=$(ps aux | grep -i 'java -jar' | grep -v grep | tr ' ' '\n' | sed -e '/^$/d' | head -2 | tail -1)
            if [[ -z $PROCESS_ID ]]; then
                echo 'Nothing Process Running'
                if [[ -d $BACKUP_TMP_DIR ]]; then
                    cp -R $BACKUP_TMP_DIR/* $BACKUP_DIR
                    rm -rf $BACKUP_TMP_DIR
                fi
            else
                echo 'Another Process Running'
                if [[ -d $BACKUP_DIR ]]; then
                    mkdir -p "$BACKUP_TMP_DIR"
                    cp -R $BACKUP_DIR/* $BACKUP_TMP_DIR
                fi
                kill -9 $PROCESS_ID
            fi
            nohup java --enable-preview -jar -Duser.timezone=Asia/Seoul -Dspring.profiles.active=${{ secrets.SPRING_PROFILE }} $EXECUTABLE_SPRING_JAR_PATH > $SOURCE_DIR/build/libs/output.log 2>&1 &
            sleep 1
